// Full parity sweep: for every (electricity, gas, scenario) in
// tests/fixtures/parity.json, the TS simulator must match the Python
// simulator's output within EUR 0.01.
//
// The fixture is regenerated by:
//     python web/scripts/gen_parity_fixture.py
// Run that after any change to:
//   - tariffs/*.yaml (catalogue)
//   - tariffs/profiles/*.yaml (load profile)
//   - src/simulator.py or src/profiles.py (math)
//
// Commit the regenerated fixture so CI catches drift on the next run.

import { describe, expect, it } from "vitest";

import tariffsJson from "../public/tariffs.json";
import profilesJson from "../public/profiles.json";
import parityFixture from "./fixtures/parity.json";

import {
  annualDualFuelCostEur,
  cheapestBandEvDistribution,
} from "../src/simulator";
import { toSnapshot, type RawTariffData } from "../src/tariffLoader";
import {
  DEFAULT_PROFILE_ID,
  scaleProfileToAnnualKwh,
  toProfiles,
  type RawProfilesData,
} from "../src/profiles";

type Scenario = {
  label: string;
  annual_elec_kwh: number;
  gas_annual_kwh: number;
  ev_annual_kwh: number;
  ev_mode: "none" | "current" | "shifted";
};

type ParityRow = {
  scenario_id: string;
  electricity_id: string;
  gas_id: string;
  expected_eur: number;
};

type ParityFixture = {
  generated_with: string;
  scenarios: Record<string, Scenario>;
  ev_hours_current: Record<string, number>;
  results: ParityRow[];
};

const fixture = parityFixture as ParityFixture;
const snapshot = toSnapshot(tariffsJson as unknown as RawTariffData);
const profiles = toProfiles(profilesJson as unknown as RawProfilesData);
const profile = profiles[DEFAULT_PROFILE_ID];

const evHoursCurrent: Record<number, number> = Object.fromEntries(
  Object.entries(fixture.ev_hours_current).map(([k, v]) => [Number(k), v]),
);

// One scaled profile per scenario, cached so we don't rescale per row.
const scaledByScenario = new Map<
  string,
  { weekday: number[]; weekend: number[] }
>();
for (const [id, sc] of Object.entries(fixture.scenarios)) {
  const [weekday, weekend] = scaleProfileToAnnualKwh(
    profile.weekday,
    profile.weekend,
    sc.annual_elec_kwh,
  );
  scaledByScenario.set(id, { weekday, weekend });
}

describe("parity sweep: TS simulator matches Python within EUR 0.01", () => {
  for (const row of fixture.results) {
    const scenario = fixture.scenarios[row.scenario_id];
    const elecPlan = snapshot.electricity[row.electricity_id];
    const gasPlan = snapshot.gas[row.gas_id];
    const scaled = scaledByScenario.get(row.scenario_id)!;

    const testName =
      `[${row.scenario_id}] ${row.electricity_id} + ${row.gas_id}` +
      ` → EUR ${row.expected_eur.toFixed(2)}`;

    it(testName, () => {
      expect(elecPlan, `missing elec plan ${row.electricity_id}`).toBeDefined();
      expect(gasPlan, `missing gas plan ${row.gas_id}`).toBeDefined();

      let evDist: Record<number, number> | undefined;
      if (scenario.ev_mode === "none") {
        evDist = undefined;
      } else if (scenario.ev_mode === "current") {
        evDist = evHoursCurrent;
      } else if (scenario.ev_mode === "shifted") {
        evDist =
          elecPlan.kind === "flat"
            ? evHoursCurrent
            : cheapestBandEvDistribution(elecPlan);
      }

      const cost = annualDualFuelCostEur({
        weekdayHourly: scaled.weekday,
        weekendHourly: scaled.weekend,
        elecPlan,
        gasPlan,
        gasAnnualKwh: scenario.gas_annual_kwh,
        evAnnualKwh: scenario.ev_annual_kwh,
        evDistribution: evDist,
      });

      expect(cost).toBeCloseTo(row.expected_eur, 2);
    });
  }
});
